### ISSUE TITLE
Unregister notification!

### ISSUE THREAD

**Issue by welldone217** [Tobiaswk/scheduled_notifications#3] opened 2018-02-06 08:53 UTC
D/dk.kjeldsen.scheduled_notifications.ScheduleNotificationsManager( 4938): Register notification!
D/dk.kjeldsen.scheduled_notifications.ScheduleNotificationsManager( 4938): Saved scheduled notification!
I/flutter ( 4938): 1783802548
D/dk.kjeldsen.scheduled_notifications.ScheduleNotificationsService( 4938): Service start
D/dk.kjeldsen.scheduled_notifications.ScheduleNotificationsManager( 4938): Unregister notification!

what i can do?

**Comment by Tobiaswk** [comment] 2018-02-06 10:20
@welldone217 I'm not entirely sure what you problem is? It seems to me that it is working as intended.

**Comment by Tobiaswk** [comment] 2018-04-04 08:48
Closing this issue. No feedback.

**Closed as completed by Tobiaswk** 2018-04-04 08:48 UTC

**Comment by Stnieder** [comment] 2018-12-05 21:30
I do have the problem as @welldone217. In the console everything runs fine, but there is no notification showing up.

**Comment by stnieder** [comment] 2018-12-05 21:36
> D/dk.kjeldsen.scheduled_notifications.ScheduleNotificationsManager( 4938): Register notification!
> D/dk.kjeldsen.scheduled_notifications.ScheduleNotificationsManager( 4938): Saved scheduled notification!
> I/flutter ( 4938): 1783802548
> D/dk.kjeldsen.scheduled_notifications.ScheduleNotificationsService( 4938): Service start
> D/dk.kjeldsen.scheduled_notifications.ScheduleNotificationsManager( 4938): Unregister notification!
> 
> what i can do?

I do have the problem as @welldone217. In the console everything runs fine, but there is no notification showing up.

**Comment by tusharpandey** [comment] 2019-02-14 05:41
Yes same in my case, no notification.

**Comment by Fabio91** [comment] 2020-04-09 13:56
Same in my case, no notification.

**Comment by feliciaeponou** [comment] 2021-03-29 09:43
Hello ! Have you found a solution ? I am facing the same issue.

**Comment by Tobiaswk** [comment] 2021-03-29 14:15
This package is not maintained any longer.

Den 29. marts 2021 11.43.57 CEST, Felicia Eponou ***@***.***> skrev:
